#!/bin/sh

# installing packages from 'packages' file
doas apk add $(grep -vE "^\s*#" packages  | tr "\n" " ")

# installing packages from flatpak
doas flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
doas flatpak install flathub com.discordapp.Discord -y

# installing ufetch
doas mv ufetch /usr/bin/

# installing oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

cp -f .zshrc $HOME

cp -f -r .config/* $HOME/.config


mkdir $HOME/wallpapers
cp -f wallpapers/* $HOME/wallpapers
