#!/bin/sh

mkdir .config .config/i3 .config/i3status .config/dunst .config/kitty

cp -f /home/$(whoami)/.config/i3/config .config/i3/
cp -f /home/$(whoami)/.config/i3status/config .config/i3status/

cp -f /home/$(whoami)/.config/dunst/dunstrc .config/dunst

cp -f /home/$(whoami)/.config/kitty/* .config/kitty

cp -f /home/$(whoami)/.zshrc .
